global:
  scrape_interval: 15s  # Set the default scrape interval (optional)

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: [ 'app:8000' ]
  - job_name: 'nginx'
    static_configs:
      - targets: [ 'nginx:80' ]
  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgres:5432' ]
  - job_name: 'cassandra'
    static_configs:
      - targets: [ 'cassandra:9042' ]
