global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['app:8000', 'app:8001', 'app:8002']
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8000']
